// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oistfhpvqtczsmlremsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pc3RmaHB2cXRjenNtbHJlbXNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NTg1MDQsImV4cCI6MjA2MzEzNDUwNH0.2ooX4kYNLfZF9dC8UNuydHl7rSpmIY2riUogOrabA_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);